# Spring 配置
spring:
  # 数据源配置文件
  profiles:
    active: druid

  # 开发工具，配置热部署
  devtools:
    restart:
      enabled: true #热部署
  freemarker:
    cache: false #页面不开启缓存，修改即生效

  # jackson日期格式配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  # mvc日期格式配置
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss

  # 文件上传大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
  application:
    name: gouyan-cinema

# Mybatis 配置
mybatis:
  type-aliases-package: com.gouyan.**.domin #指定封装到实体类的包，省去书写全类名
  mapper-locations: classpath*:mapper/**/*Mapper.xml #mapper配置文件的位置
  configuration:
    map-underscore-to-camel-case: true #配置开启驼峰式命名

# logging 日志配置
logging:
  level:
    com.gouyan: trace
    org.springframework: warn

# pagehelper 分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 9006

# anji-plus验证码配置
aj:
  captcha:
    water-mark:


eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://127.0.0.1:7002/eureka
  instance:
    instance-id:  ${spring.application.name}:${server.port}

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms
